# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Project Hexagon
github_username:  muskaanX

baseurl: "/about"

assets:
  sources:
    - _assets
    
# Build settings
theme: "just-the-docs"
plugins:
  - jekyll-feed

aux_links:
  "GitHub Repository": "https://github.com/muskaanX/Hexagon"

color_scheme: dark

include:
  - "favicon.ico"
  
nav:
  - title: "About"
    url: "/about"
  - title: "Working"
    url: "/working"
  - title: "Features"
    url: "/features"
  - title: "Do-it-yourself"
    url: "/do-it-yourself"
    children:
      - title: "Overview & Tips"
        url: "/do-it-yourself/overview"
      - title: "3D Printing"
        url: "/do-it-yourself/3d-printing"
      - title: "Electronics"
        url: "/do-it-yourself/electronics"
      - title: "Bill of Materials"
        url: "/do-it-yourself/bill-of-materials"
      - title: "Firmware"
        url: "/do-it-yourself/firmware"
      - title: "Assembly"
        url: "/do-it-yourself/assembly"
        children:
        - title: "PCB"
          url: "/assembly/1-pcb"
        - title: "ESP32"
          url: "/assembly/2-esp32"
  - title: "Iterations"
    url: "/iterations"
    children:
      - title: "Version 1"
        url: "/iterations/version-1"
      - title: "Version 2"
        url: "/iterations/version-2"
      - title: "Version 3"
        url: "/iterations/version-3"
  - title: "Advanced"
    url: "/advanced"
  - title: "Simulation"
    url: "/simulation"
  - title: "Gallery"
    url: "/gallery"
  - title: "Animations"
    url: "/animation"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
